# Generated by Django 3.2.8 on 2022-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Topic')),
                ('description', models.CharField(max_length=250, verbose_name='Message Text')),
                ('price', models.IntegerField(default=0)),
                ('discount_rate', models.IntegerField(default=0)),
                ('on_sale', models.BooleanField(default=True)),
            ],
        ),
    ]
