# Generated by Django 3.2.8 on 2022-01-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('discount_rate', models.IntegerField(default=0, verbose_name='Discount Rate %')),
                ('on_sale', models.BooleanField(default=True, verbose_name='On Sale')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
