# Generated by Django 3.2.9 on 2021-12-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Surname', models.CharField(max_length=120)),
                ('Mail', models.EmailField(max_length=120)),
                ('content', models.TextField(verbose_name='Feedback')),
            ],
        ),
    ]
