# Generated by Django 3.2.8 on 2021-12-23 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, verbose_name='Day of week')),
                ('start_time', models.TimeField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarevent', to='trainer.trainer', verbose_name='Trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Reservation Date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='trainer.calendarevent', verbose_name='Calendar Event')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='trainer.trainer', verbose_name='Trainer')),
            ],
        ),
    ]
