# Generated by Django 3.2.8 on 2021-12-23 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_calendarevent_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='start_time',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateField(auto_now_add=True, verbose_name='Reservation Date'),
        ),
    ]
