# Generated by Django 3.2.7 on 2021-12-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20211223_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateField(verbose_name='Reservation Date'),
        ),
    ]
