# Generated by Django 3.2.8 on 2022-01-04 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.CharField(default='konu', max_length=120, verbose_name='Topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(max_length=250, verbose_name='Message Text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
    ]
